<?php

namespace Monogo\Alphabank\Gateway\Http\Converter;

class HtmlFormConverter extends \Magento\Payment\Gateway\Http\Converter\HtmlFormConverter
{
    /**
     * @param string $response
     * @return array
     * @throws \Magento\Payment\Gateway\Http\ConverterException
     */
    public function convert($response)
    {
        return parent::convert($response); // TODO: Change the autogenerated stub
    }
}
